Add a missing runtime dependency, py-libxml2. Got a bite when tried to update epiphany to 1.7.3 and got error like this:
# /usr/X11R6/bin/xml2po
Traceback (most recent call last):
  File "/usr/X11R6/bin/xml2po", line 34, in ?
    import libxml2
ImportError: No module named libxml2


git-svn-id: svn://creme-brulee.marcuscom.com/ports/trunk@4329 df743ca5-7f9a-e211-a948-0013205c9059