Fix the login dialog, same hack that I did with Cinnamon. Before this patch, the gnome-shell/Cinnamon will boot up without login dialog that there is no way for you to log into GNOME desktop. I am not sure why the Object.keys(obj) doesn't work though. Probably because of the libxul that I don't really dig in it deeper. It was introduced in JavaScript 1.8.5, so I don't know what version of JavaScript in libxul.
https://developer.mozilla.org/en/JavaScript/Reference/Global_Objects/Object/keys

In the /var/log/gdm/:0-greeter.log shows:
------------------------------------------
    JS ERROR: !!!   Exception was: TypeError: Object.keys is not a function
    JS ERROR: !!!     lineNumber = '305'
    JS ERROR: !!!     fileName = '"/usr/local/share/gnome-shell/js/gdm/loginDialog.js"'
    JS ERROR: !!!     stack = '"()@/usr/local/share/gnome-shell/js/gdm/loginDialog.js:305
------------------------------------------

Bump the PORTREVISION.


git-svn-id: svn://creme-brulee.marcuscom.com/ports/trunk@16702 df743ca5-7f9a-e211-a948-0013205c9059